import type { Product } from "../app/types/product";

function humanize(fileName: string) {
  return fileName.replace(/\.[^/.]+$/, "").replace(/[-_]+/g, " ");
}

/** Détecte un nom de fichier auto-généré par Drive (format UUID). */
function looksAutoGenerated(fileNameWithoutExtension: string): boolean {
  const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  return uuidPattern.test(fileNameWithoutExtension.trim());
}

export function driveImageUrl(fileId: string, width = 900) {
  return `https://drive.google.com/thumbnail?id=${fileId}&sz=w${width}`;
}

export async function getDriveProducts(
  folderId = process.env.GOOGLE_DRIVE_FOLDER_ID
): Promise<Product[]> {
  const apiKey = process.env.GOOGLE_DRIVE_API_KEY;

  if (!apiKey || !folderId) {
    console.error("Google Drive API key or folder ID is missing.");
    return [];
  }

  const params = new URLSearchParams({
    key: apiKey,
    q: `'${folderId}' in parents and mimeType contains 'image/' and trashed = false`,
    orderBy: "name",
    fields: "files(id,name,mimeType)",
    pageSize: "100",
  });

  const url = `https://www.googleapis.com/drive/v3/files?${params}`;

  try {
    const response = await fetch(url, {
      next: { revalidate: 300 },
    });

    if (!response.ok) {
      const text = await response.text();
      console.error("Google Drive API request failed:", response.status, text);
      return [];
    }

    const data = await response.json();

    if (!data.files || !Array.isArray(data.files)) {
      console.error("Google Drive API returned invalid data.", data);
      return [];
    }

    return data.files.map((file: { id: string; name: string }, index: number) => {
      const id = String(index + 1).padStart(2, "0");
      const rawName = file.name.replace(/\.[^/.]+$/, "").trim();
      const name = looksAutoGenerated(rawName) ? "" : humanize(file.name);

      return {
        id,
        name,
        imageUrl: driveImageUrl(file.id),
        imageAlt: name || `Tenue ${id}`,
      };
    });
  } catch (error) {
    console.error("Google Drive API request error:", error);
    return [];
  }
}